#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="tmux,herdr,zsh,nvim,ghostty,zed,lazygit,yazi,agents,claude,atuin,git"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/repos/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
