#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="tmux,zsh,nvim,ghostty,zed"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/repos/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
