#!/usr/bin/env python3
"""
Export herdr's CURRENT workspaces to a standalone restore script.

herdr already persists workspaces natively (~/.config/herdr/session.json), so
this is not needed for day-to-day use — it's for snapshotting a known-good
layout you can re-create later, commit to dotfiles, or replay on another machine.

    python3 herdr-export.py                 # -> herdr-restore.py
    python3 herdr-export.py --out snap.py   # custom output path
    python3 herdr-export.py --list          # just print what's there
    python3 herdr-export.py --skip w1       # omit workspace(s) by name/id

The generated script recreates workspaces -> tabs -> split panes (with cwds and
split ratios) over herdr's socket API. Panes open as plain shells.
"""
import json, os, sys

SESSION = os.path.expanduser("~/.config/herdr/session.json")


def to_tree(node, panes):
    """herdr session layout node -> layout.apply tree."""
    if "Pane" in node:
        pid = str(node["Pane"])
        return {"type": "pane", "cwd": panes.get(pid, {}).get("cwd")}
    s = node["Split"]
    return {
        "type": "split",
        "direction": "right" if s["direction"] == "Horizontal" else "down",
        "ratio": round(float(s.get("ratio", 0.5)), 3),
        "first": to_tree(s["first"], panes),
        "second": to_tree(s["second"], panes),
    }


def first_cwd(t):
    while t.get("type") == "split":
        t = t["first"]
    return t.get("cwd")


def collect(skip, keep_unnamed=False):
    if not os.path.exists(SESSION):
        sys.exit(f"no herdr session state at {SESSION}")
    data = json.load(open(SESSION, encoding="utf-8"))
    out = []
    dropped = 0
    for w in data.get("workspaces", []):
        label = w.get("custom_name") or w.get("id")
        if label in skip:
            continue
        tabs = []
        for t in w.get("tabs", []):
            panes = t.get("panes") or {}
            layout = t.get("layout")
            if not layout:
                continue
            root = to_tree(layout, panes)
            name = t.get("custom_name")
            # `workspace.create` auto-creates an empty default tab; it shows up
            # as an unnamed single-pane tab. Drop it so restores stay clean.
            if not keep_unnamed and not name and root.get("type") == "pane":
                dropped += 1
                continue
            tabs.append({"tab_label": name, "root": root})
        if not tabs:
            continue
        out.append({
            "label": label,
            "cwd": w.get("identity_cwd") or first_cwd(tabs[0]["root"]),
            "tabs": tabs,
        })
    if dropped:
        print(f"(dropped {dropped} empty auto-created default tab(s) — --keep-unnamed to retain)\n")
    return out


TEMPLATE = '''#!/usr/bin/env python3
"""
herdr workspace restore — generated by herdr-export.py from a live session.

PREREQ: herdr must be RUNNING.
    python3 {script}              # recreate the workspaces
    python3 {script} --dry-run    # preview only
    python3 {script} --undo       # close workspaces with these names
"""
import socket, json, os, sys

WORKSPACES = json.loads(r\'\'\'
__DATA__
\'\'\')

SOCK = os.environ.get("HERDR_SOCKET_PATH") or os.path.expanduser("~/.config/herdr/herdr.sock")
DRY  = "--dry-run" in sys.argv
UNDO = "--undo" in sys.argv
HOME = os.path.expanduser("~")
warnings = []
_rid = 0


def send(method, params):
    """One request per connection — herdr closes the socket after each response."""
    global _rid
    if not os.path.exists(SOCK):
        sys.exit(f"herdr socket not found at {{SOCK}}\\nStart herdr first, then re-run.")
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.connect(SOCK)
    f = s.makefile("rwb")
    _rid += 1
    rid = f"restore_{{_rid}}"
    result = {{}}
    try:
        f.write((json.dumps({{"id": rid, "method": method, "params": params}}) + "\\n").encode())
        f.flush()
        while True:
            line = f.readline()
            if not line:
                break
            msg = json.loads(line.decode())
            if msg.get("id") != rid:
                continue
            if "error" in msg:
                raise RuntimeError(f"{{method}}: {{msg['error']}}")
            result = msg.get("result", {{}})
            break
    except BrokenPipeError:
        raise RuntimeError(f"{{method}}: herdr closed the connection")
    finally:
        try:
            f.close()
        except Exception:
            pass
        s.close()
    return result


def find_id(obj):
    if isinstance(obj, dict):
        for n in ("id", "workspace_id"):
            if isinstance(obj.get(n), str):
                return obj[n]
        for v in obj.values():
            r = find_id(v)
            if r:
                return r
    return None


def resolve(cwd, root):
    for c in (cwd, root, HOME):
        if c and os.path.isdir(c):
            if c != cwd:
                warnings.append(f"  {{cwd!r}} missing -> {{c!r}}")
            return c
    return HOME


def fix(node, root):
    if node["type"] == "pane":
        node["cwd"] = resolve(node.get("cwd"), root)
    else:
        fix(node["first"], root)
        fix(node["second"], root)
    return node


def main():
    if DRY:
        for w in WORKSPACES:
            print(f"workspace {{w['label']!r}} (cwd {{w['cwd']}})")
            for t in w["tabs"]:
                print(f"  tab {{t['tab_label']!r}}")
        print("\\n(dry run — nothing created)")
        return

    send("ping", {{}})

    if UNDO:
        labels = {{w["label"] for w in WORKSPACES}}
        res = send("workspace.list", {{}})
        def walk(o):
            found = []
            if isinstance(o, dict):
                if o.get("label") in labels and find_id(o):
                    found.append((o["label"], find_id(o)))
                for v in o.values():
                    found += walk(v)
            elif isinstance(o, list):
                for v in o:
                    found += walk(v)
            return found
        n = 0
        for label, wid in walk(res):
            send("workspace.close", {{"workspace_id": wid}})
            print(f"closed {{label!r}}")
            n += 1
        print(f"undo complete — closed {{n}} workspace(s)")
        return

    for i, w in enumerate(WORKSPACES):
        res = send("workspace.create", {{"label": w["label"], "cwd": resolve(w["cwd"], HOME)}})
        if i == 0:
            print(f"    (workspace.create response: {{json.dumps(res)[:200]}})")
        wid = find_id(res)
        if not wid:
            sys.exit(f"could not read workspace id: {{json.dumps(res)[:300]}}")
        print(f"workspace {{w['label']!r}} -> {{wid}}")
        for t in w["tabs"]:
            root = fix(json.loads(json.dumps(t["root"])), w["cwd"] or HOME)
            params = {{"workspace_id": wid, "focus": False, "root": root}}
            if t.get("tab_label"):
                params["tab_label"] = t["tab_label"]
            send("layout.apply", params)
            print(f"    tab {{t['tab_label']!r}}")

    print(f"\\ndone — restored {{len(WORKSPACES)}} workspaces.")
    if warnings:
        print("substituted missing directories:")
        print("\\n".join(warnings))


if __name__ == "__main__":
    main()
'''


def main():
    argv = sys.argv[1:]
    skip = set()
    if "--skip" in argv:
        i = argv.index("--skip")
        skip = set(argv[i + 1].split(","))
    out = "herdr-restore.py"
    if "--out" in argv:
        out = argv[argv.index("--out") + 1]

    ws = collect(skip, keep_unnamed="--keep-unnamed" in argv)
    tabs = sum(len(w["tabs"]) for w in ws)
    panes = sum(json.dumps(t["root"]).count('"type": "pane"') for w in ws for t in w["tabs"])

    for w in ws:
        print(f"{w['label']:14} {len(w['tabs'])} tab(s)   {w['cwd']}")
        for t in w["tabs"]:
            print(f"    - {t['tab_label']}")
    print(f"\n{len(ws)} workspaces, {tabs} tabs, {panes} panes")

    if "--list" in argv:
        return

    script = TEMPLATE.format(script=os.path.basename(out)).replace("__DATA__", json.dumps(ws, indent=2))
    open(out, "w", encoding="utf-8").write(script)
    os.chmod(out, 0o755)
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
