return {}
-- return {
--   dir = "/Users/webhooked/repos/private/themes/neovim/night-owl.nvim",
--   name = "night-owl",
--   lazy = false,
--   priority = 1000,
--   dev = true,
--   opts = {
--     bold = false,
--     italics = false,
--     -- transparent_background = true,
--   },
-- }
