return {
  "rose-pine/neovim",
  name = "rose-pine",
  enabled = false,
  lazy = false,
  priority = 1000,
  opts = {
    variant = "auto",
    -- light_variant = "dawn",
    -- dark_variant = "moon",
    styles = {
      italic = false,
      transparency = true,
    },
    highlight_groups = {
      BufferLineBackground = { bg = "NONE" },
      BufferLineBuffer = { bg = "NONE" },
      BufferLineBufferSelected = { bg = "NONE" },
      BufferLineBufferVisible = { bg = "NONE" },
      BufferLineCloseButton = { bg = "NONE" },
      BufferLineCloseButtonSelected = { bg = "NONE" },
      BufferLineCloseButtonVisible = { bg = "NONE" },
      BufferLineDuplicate = { bg = "NONE" },
      BufferLineDuplicateSelected = { bg = "NONE" },
      BufferLineDuplicateVisible = { bg = "NONE" },
      BufferLineError = { bg = "NONE", sp = "NONE" },
      BufferLineErrorDiagnostic = { bg = "NONE", sp = "NONE" },
      BufferLineErrorDiagnosticSelected = { bg = "NONE", sp = "NONE" },
      BufferLineErrorDiagnosticVisible = { bg = "NONE" },
      BufferLineErrorSelected = { bg = "NONE", sp = "NONE" },
      BufferLineErrorVisible = { bg = "NONE" },
      BufferLineFill = { bg = "NONE" },
      BufferLineHint = { sp = "NONE", bg = "NONE" },
      BufferLineHintDiagnostic = { sp = "NONE", bg = "NONE" },
      BufferLineHintDiagnosticSelected = { bg = "NONE", sp = "NONE" },
      BufferLineHintDiagnosticVisible = { bg = "NONE" },
      BufferLineHintSelected = { bg = "NONE", sp = "NONE" },
      BufferLineHintVisible = { bg = "NONE" },
      BufferLineInfo = { sp = "NONE", bg = "NONE" },
      BufferLineInfoDiagnostic = { sp = "NONE", bg = "NONE" },
      BufferLineInfoDiagnosticSelected = { sp = "NONE", bg = "NONE" },
      BufferLineInfoDiagnosticVisible = { bg = "NONE" },
      BufferLineInfoSelected = { bg = "NONE", sp = "NONE" },
      BufferLineInfoVisible = { bg = "NONE" },
      BufferLineIndicatorSelected = { bg = "NONE" },
      BufferLineModified = { bg = "NONE" },
      BufferLineModifiedSelected = { bg = "NONE" },
      BufferLineModifiedVisible = { bg = "NONE" },
      BufferLineNumbers = { bg = "NONE" },
      BufferLineNumbersSelected = { bg = "NONE" },
      BufferLineNumbersVisible = { bg = "NONE" },
      BufferLineOffsetSeparator = { bg = "NONE" },
      BufferLineSeparator = { bg = "NONE" },
      BufferLineSeparatorSelected = { bg = "NONE" },
      BufferLineSeparatorVisible = { bg = "NONE" },
      BufferLineTab = { bg = "NONE" },
      BufferLinePick = { bg = "NONE" },
      BufferLinePickSelected = { bg = "NONE" },
      BufferLineDevIconLua = { bg = "NONE" },
      BufferLineDevIconLuaSelected = { bg = "NONE" },
      BufferLineDevIconLuaVisible = { bg = "NONE" },
      BufferLineDevIconLuaInactive = { bg = "NONE" },
      BufferLinePickVisible = { bg = "NONE" },
      BufferLineIndicatorVisible = { bg = "NONE" },
      BufferLineTabClose = { bg = "NONE" },
      BufferLineTabSelected = { bg = "NONE" },
      BufferLineTabSeparator = { bg = "NONE" },
      BufferLineTabSeparatorSelected = { bg = "NONE" },
      BufferLineTruncMarker = { bg = "NONE" },
      BufferLineWarning = { bg = "NONE" },
      BufferLineWarningDiagnostic = { bg = "NONE" },
      BufferLineWarningDiagnosticSelected = { bg = "NONE" },
      BufferLineWarningDiagnosticVisible = { bg = "NONE" },
      BufferLineWarningSelected = { bg = "NONE" },
      BufferLineWarningVisible = { bg = "NONE" },
      SagaBorder = { bg = "NONE" },
      SagaNormal = { bg = "NONE" },
      SagaExpand = { bg = "NONE" },
      -- WinSeparator = { fg = "NONE", bg = "" },
    },
  },
}
